import {
  List,
  ArrowLeft,
  Stack,
  Books,
  PresentationChart,
  QrCode,
  User,
  Newspaper,
  SignOut,
  Pencil,
  Plus,
  DotsThree,
  Trash,
  Handshake,
  PencilLine,
  FilePdf,
  CalendarCheck,
  UserFocus,
  CheckSquare,
  InstagramLogo,
  SignIn,
  GameController,
  Users,
} from "@phosphor-icons/react";
export const DefaultsIcons = {
  MenuIcon: List,
  BackIcon: ArrowLeft,
  DashboarIcon: Stack,
  MiniCursorIcon: Books,
  PalestranteIcon: PresentationChart,
  PresencaIcon: QrCode,
  ApoiadoresIcon: Handshake,
  ParticipantesIcon: User,
  InscricaoEventoIcon: PencilLine,
  NoticiasIcon: Newspaper,
  LogOff: SignOut,
  LogIn: SignIn,
  EditIcon: Pencil,
  AdicionarIcon: Plus,
  DotsIcon: DotsThree,
  ApagarIcon: Trash,
  ExportPdfIcon: FilePdf,
  EventosIcon: CalendarCheck,
  CrachasIcon: UserFocus,
  CalendarIcon: CalendarCheck,
  EventoVigenteIcon: CheckSquare,
  InstagramIcon: InstagramLogo,
  CompeticaoIcon: GameController,
  EquipeIcon: Users,
};
